server:
  port: 8082
  servlet:
    context-path: /identity

spring:
  datasource:
    #nếu biến DBMS_CONNECTION chưa khởi tạo sẽ lấy giá trị sau dấu :
    url: ${DBMS_CONNECTION:jdbc:mysql::/localhost:3306/identity_service}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "hEoxvhp+9WoCrvHn+6mStpc6FhPbQakBylCVWvz0LzechI/vY3GsZosYDmXmABLh"
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second